apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    version: 1

  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"
    version: 1

  # Jaeger datasource for tracing
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          { key: 'service.name', value: 'service' }
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
    version: 1

  # Elasticsearch datasource (if using ELK stack)
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logstash-*"
    editable: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.9.0"
    version: 1

  # PostgreSQL datasource for business metrics
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: trading_db
    user: trading_user
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: true
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    version: 1

  # InfluxDB datasource (if using for time series data)
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: trading_metrics
    user: influx_user
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}
    editable: true
    jsonData:
      httpMode: GET
      version: "1.8"
    version: 1

  # Redis datasource (using Redis plugin)
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    editable: true
    jsonData:
      client: "standalone"
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    version: 1

  # TestData datasource for testing dashboards
  - name: TestData
    type: testdata
    access: proxy
    editable: true
    version: 1